import Foundation

struct ExpenseCategory: Identifiable {
    let id = UUID()
    let name: String
    let nameGreek: String
    let deductiblePercent: String
    let cap: String?
    let legalReference: String
    let notes: String
    let icon: String
}

extension ExpenseCategory {
    static let all: [ExpenseCategory] = [
        ExpenseCategory(name: "Rent (Business)", nameGreek: "Ενοίκιο Επαγγελματικής Στέγης",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Full deduction for premises used exclusively for business. If mixed use, proportional deduction applies.",
                        icon: "building"),
        ExpenseCategory(name: "Home Office", nameGreek: "Χώρος κατ' οίκον εργασίας",
                        deductiblePercent: "40–60%", cap: "Proportional to use",
                        legalReference: "Ν. 4172/2013, Άρθρο 22, ΠΟΛ. 1079/2015",
                        notes: "If you work from home, a percentage of rent/mortgage, utilities, and maintenance can be deducted based on the space used.",
                        icon: "house"),
        ExpenseCategory(name: "Utility Bills", nameGreek: "Λογαριασμοί Κοινής Ωφέλειας",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Electricity, water, internet, phone for business use. Keep original bills.",
                        icon: "bolt"),
        ExpenseCategory(name: "Office Supplies", nameGreek: "Γραφική Ύλη & Αναλώσιμα",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Common practice, Ν. 4308/2014",
                        notes: "Paper, ink, stationery, printer cartridges, small office equipment under €1,500.",
                        icon: "pencil.and.outline"),
        ExpenseCategory(name: "Professional Services", nameGreek: "Αμοιβές Τρίτων",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Lawyers, accountants, consultants, engineers. Must have invoice (Τιμολόγιο).",
                        icon: "person.fill.viewfinder"),
        ExpenseCategory(name: "Social Security (EFKA)", nameGreek: "Ασφαλιστικές Εισφορές (ΕΦΚΑ)",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22, Ν. 4670/2020",
                        notes: "All EFKA contributions are fully deductible from taxable income.",
                        icon: "shield.checkered"),
        ExpenseCategory(name: "Insurance Premiums", nameGreek: "Ασφάλιστρα",
                        deductiblePercent: "100%", cap: "Business insurance only",
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Professional liability insurance, health insurance for employees. Personal health insurance has separate rules.",
                        icon: "heart.text.square"),
        ExpenseCategory(name: "Vehicle Expenses", nameGreek: "Δαπάνες Οχήματος",
                        deductiblePercent: "50%", cap: "Business use only",
                        legalReference: "ΠΟΛ. 1113/2015",
                        notes: "Fuel, maintenance, insurance, lease payments. 50% is automatically accepted. 100% if you can prove exclusive business use.",
                        icon: "car"),
        ExpenseCategory(name: "Travel & Transportation", nameGreek: "Ταξίδια & Μετακινήσεις",
                        deductiblePercent: "100%", cap: "Business purpose only",
                        legalReference: "Ν. 4172/2013, Άρθρο 23",
                        notes: "Airfare, train, taxi, tolls, parking for business purposes. Keep receipts and document business reason.",
                        icon: "airplane"),
        ExpenseCategory(name: "Meals & Entertainment", nameGreek: "Διατροφή & Φιλοξενία",
                        deductiblePercent: "30%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 23",
                        notes: "Business meals with clients, suppliers. Only 30% of the expense is deductible. Must have itemized receipt.",
                        icon: "fork.knife"),
        ExpenseCategory(name: "Education & Training", nameGreek: "Εκπαίδευση & Κατάρτιση",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Courses, seminars, conferences, certifications related to your profession.",
                        icon: "book"),
        ExpenseCategory(name: "Technology & Software", nameGreek: "Τεχνολογία & Λογισμικό",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22, Ν. 4308/2014",
                        notes: "Software licenses, SaaS subscriptions, domain names, hosting, cloud services, website maintenance.",
                        icon: "desktopcomputer"),
        ExpenseCategory(name: "Equipment (over €1,500)", nameGreek: "Εξοπλισμός (άνω των €1.500)",
                        deductiblePercent: "100%", cap: "Depreciated over 5 years",
                        legalReference: "Ν. 4172/2013, Άρθρο 24, Ν. 4308/2014",
                        notes: "Computers, laptops, printers, phones over €1,500 are depreciated over 5 years (20%/year). Under €1,500: fully deductible immediately.",
                        icon: "printer"),
        ExpenseCategory(name: "Advertising & Marketing", nameGreek: "Διαφήμιση & Προβολή",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Google Ads, social media ads, website promotion, printed materials, banners, business cards.",
                        icon: "megaphone"),
        ExpenseCategory(name: "Bank & Transaction Fees", nameGreek: "Τραπεζικά & Συναλλαγές",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Common practice",
                        notes: "Bank account fees, POS terminal fees, credit card processing fees, money transfer costs.",
                        icon: "creditcard"),
        ExpenseCategory(name: "Telecommunications", nameGreek: "Τηλεπικοινωνίες",
                        deductiblePercent: "100%", cap: nil,
                        legalReference: "Ν. 4172/2013, Άρθρο 22",
                        notes: "Mobile phone plan, landline, internet connection. For mixed personal/business use, keep a separate business line.",
                        icon: "antenna.radiowaves.left.and.right"),
    ]
}
